version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    build: 
      context: api
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  ui:
    image: ui
    build:
      context: ui
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

volumes:
  mongo_volume: